# Generated by Django 3.1.5 on 2021-01-26 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20210125_2228'),
        ('atracoes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Atracoes',
            new_name='Atracao',
        ),
    ]
